uploads = []
generated = []

[[outputs]]
id = "ZDtnh1q2UJrRHuCUZZJz3"
uri = "file://android/app/build/outputs/apk/debug/app-debug.apk"
type = "unspecified"
title = "NovaCycle debug APK (locally rebuilt)"

[[outputs]]
id = "IBvVXXKxQ_AhoN0632KGJ"
uri = "file://android/app/build/outputs/apk/release/app-release.apk"
type = "unspecified"
title = "NovaCycle release APK (locally rebuilt, debug-signed fallback)"
