uploads = []
generated = []

[[outputs]]
id = "6KmVxvqeeZLomgSlW7JP2"
uri = "file://android/app/build/outputs/apk/debug/app-debug.apk"
type = "unspecified"
title = "NovaCycle chart upgrade — debug APK"
